services:
  cz-front-dev:
    image: ghcr.io/q300z/cesizen-vue:dev
    container_name: cz-front-dev
    restart: unless-stopped
    labels:
      - "traefik.enable=true"  # Activer Traefik pour ce service
      - "traefik.http.routers.cz-front-dev.rule=Host(`cesizen-dev.qalpuch.cc`)"  # Règle de routage pour le service front
      - "traefik.http.routers.cz-front-dev.entrypoints=websecure"  # Utiliser le point d'entrée HTTPS
      - "traefik.http.routers.cz-front-dev.tls.certresolver=cloudflare"  # Utiliser le résolveur de certificats Cloudflare
      - "traefik.http.services.cz-front-dev.loadbalancer.server.port=80"  # Port interne du service front
    depends_on:
      cz-api-dev:
        required: true
        condition: service_healthy
    networks:
      - traefik  # Utiliser le réseau Traefik pour la communication entre les services

  cz-api-dev:
    image: ghcr.io/q300z/cesizen-api:dev
    container_name: cz-api-dev
    restart: unless-stopped
    labels:
      - "traefik.enable=true"  # Activer Traefik pour ce service
      - "traefik.http.routers.cz-api-dev.rule=Host(`cesizen-api-dev.qalpuch.cc`)"  # Règle de routage pour le service front
      - "traefik.http.routers.cz-api-dev.entrypoints=websecure"  # Utiliser le point d'entrée HTTPS
      - "traefik.http.routers.cz-api-dev.tls.certresolver=cloudflare"  # Utiliser le résolveur de certificats Cloudflare
      - "traefik.http.services.cz-api-dev.loadbalancer.server.port=8080"  # Port interne du service API
      - "traefik.docker.network=traefik"  # Spécifier le réseau Traefik pour ce service
    env_file: .env.dev
    volumes:
      - ./logs:/app/logs
      - ./uploads/dev:/app/uploads
    depends_on:
      cz-db-dev:
        required: true
        condition: service_healthy
    networks:
      - traefik  # Utiliser le réseau Traefik pour la communication entre les services
      - cz-db-dev # Utiliser le réseau de la base de données pour la communication
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/v1/version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 15

  cz-db-dev:
    image: postgres:17.5-alpine3.22
    container_name: cz-db-dev
    restart: unless-stopped
    env_file: .env.dev
    volumes:
      - cz_db_dev:/var/lib/postgresql/data
    networks:
      - cz-db-dev # Utiliser le réseau de la base de données pour la communication
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d cesizen"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  cz_db_dev:
    driver: local

networks:
  cz-db-dev:
    name: cz-db-dev
  traefik:
    external: true
